name: Build psf wheels

on:
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2019]
    steps:
      - uses: actions/checkout@v3
      - uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_SKIP: "pp* cp37* cp38* *musllinux* *i686 *ppc64le *s390x cp39*win*arm64 cp310*win*arm64"
          CIBW_BEFORE_BUILD: python -m pip install oldest-supported-numpy
          # CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64 ARM64 x86
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: python -m psf.psf
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
